Footer
Survival-DEV/golden-lines pull request #31
Opened 2021-02-07 21:55 UTC by bayan-404

my footer that doesn't have links yet 

![nolinksbitch](https://user-images.githubusercontent.com/57558867/107160560-b1490000-699f-11eb-9c4f-06babd9480b1.png)

2021-02-08 18:40 UTC, YakoobHammouri requested changes

2021-02-08 18:40 UTC, YakoobHammouri commented on src/Layouts/fulllayout.tsx
> -        </Grid>
this grid for responsive, make a site using the same responsive  size

2021-02-08 18:40 UTC, YakoobHammouri commented on src/components/footer/index.tsx
> +    </footer>
did you test responsive  ??
you can use grid to make it responsive

2021-02-08 18:40 UTC, YakoobHammouri commented on src/components/navbar/Style.ts
> +    },
material UI have a way you can use it  to  display flex without CSS
check this URL :  [material-ui flexbox ](https://material-ui.com/system/flexbox/)

2021-02-08 18:40 UTC, YakoobHammouri commented on src/components/footer/Style.ts
> +      margin: 14,
you can use theme spacing like  padding

2021-02-08 18:40 UTC, YakoobHammouri commented on src/Layouts/style.ts
> +      paddingTop: 100,
you can use theme spacing

2021-02-08 21:41 UTC, bayan-404 commented on src/Layouts/fulllayout.tsx
> -        </Grid>
cool but do we currently need all these Grids ? in the layout we only need the `Nav-bar `and `footer` so they can be displayed on every page that uses the `"fullLayout" `  so why adding more grids that contain nothing?
so how about adding them this way?
```js
 <main className={classes.main}>
        <Grid
          direction="column"
          container
          data-aos="fade-up"
          className={classes.root}
        >
          <Grid item xs={12}>
            <Navbar />
          </Grid>
          <Box m={2} width={1}>
            {children}
          </Box>
          <Grid item xs={12}>
            <Footer />
          </Grid>
        </Grid>
      </main>
```

2021-02-08 21:41 UTC, bayan-404 commented on src/components/footer/index.tsx
> +    </footer>
the footer is so simple , the only thing that needs to change when the screen is smaller is the width so it is responsive

2021-02-08 21:41 UTC, bayan-404 commented on src/components/navbar/Style.ts
> +    },
yeah but isn't it more clean to right it inside the `style.ts` file since we have it in every component folder anyway ?

2021-02-08 21:41 UTC, bayan-404 commented on src/components/footer/Style.ts
> +      margin: 14,
thank you I will

2021-02-09 20:36 UTC, YakoobHammouri requested changes

2021-02-09 20:36 UTC, YakoobHammouri commented on src/Layouts/fulllayout.tsx
> -        </Grid>
Box must be inside Grid

2021-02-19 14:34 UTC, YakoobHammouri commented on src/Layouts/fulllayout.tsx
> +      </div>
where is the grid ?

2021-02-19 14:41 UTC, bayan-404 commented on src/Layouts/fulllayout.tsx
> +      </div>
in progress

2021-02-20 09:43 UTC, YakoobHammouri commented on src/Layouts/fulllayout.tsx
> -        <Toolbar id="back-to-top-anchor" style={{ minHeight: 1 }} />
you need this for scrolling Top

2021-02-20 09:56 UTC, YakoobHammouri approved these changes

2021-02-20 10:00 UTC, someyaaltous approved these changes

2021-02-20 10:02 UTC, merged